arc: Реорганизовал код

diff --git a/bin/arc/arc b/bin/arc/arc
--- a/bin/arc/arc
+++ b/bin/arc/arc
@@ -1,22 +1,8 @@
 #!/usr/bin/env bash
 
-ensure_arc_primary_path_is_set() {
-    local paths=$(which -a arc   \
-                  | grep -v "$0" \
-                  | grep -v "$(realpath "$0")")
-    if [[ -z "$paths" ]]; then
-        echo "arc: primary program 'arc' not found"
-        echo "Consider visiting documentation page at 'https://docs.yandex-team.ru/devtools/intro/quick-start-guide' for more details"
-        exit 1
-    fi
-
-    local suggested_path=$(echo "$paths" | head -1)
-    if [[ -z "$ARC_PRIMARY_PATH" ]]; then
-        echo 'arc: path to primary program `ARC_PRIMARY_PATH` is not set'
-        echo "Consider adding \`export ARC_PRIMARY_PATH=$suggested_path\` to your shell configuration file"
-        exit 1
-    fi
-}
+#
+# Примеси
+#
 
 arc_--() {
     "$ARC_PRIMARY_PATH" "$@"
@@ -72,23 +58,6 @@ arc_swap() {
     arc rebase -i $commit~2
 }
 
-rebase() {
-    local command=$1
-    local commit=${2:-HEAD}
-
-    # Аналогично `GIT_SEQUENCE_EDITOR='sed -i "1 s/pick/'$command'/"'`
-    ARC_EDITOR='f() {
-        local path=$1
-
-        if [ "$(basename "$path")" = "arc-rebase-todo" ]; then
-            sed -i "1 s/pick/'$command'/" "$path"
-        else
-            "$(arc config core.editor)" "$path"
-        fi
-    }; f' \
-    arc rebase -i $commit~1
-}
-
 arc_shelve() {
     local message=$(arc show --json | jq -r '.[0].commits[0].message')
 
@@ -116,6 +85,49 @@ arc_unshelve() {
                     | perl -pe 's/^(.*?): (.*?): .*$/\2/')
     if [[ "$changes" == "Working tree changes" ]]; then
         arc stash pop --index
+    fi
+}
+
+#
+# Вспомогательные функции
+#
+
+rebase() {
+    local command=$1
+    local commit=${2:-HEAD}
+
+    # Аналогично `GIT_SEQUENCE_EDITOR='sed -i "1 s/pick/'$command'/"'`
+    ARC_EDITOR='f() {
+        local path=$1
+
+        if [ "$(basename "$path")" = "arc-rebase-todo" ]; then
+            sed -i "1 s/pick/'$command'/" "$path"
+        else
+            "$(arc config core.editor)" "$path"
+        fi
+    }; f' \
+    arc rebase -i $commit~1
+}
+
+#
+# Точка входа
+#
+
+ensure_arc_primary_path_is_set() {
+    local paths=$(which -a arc   \
+                  | grep -v "$0" \
+                  | grep -v "$(realpath "$0")")
+    if [[ -z "$paths" ]]; then
+        echo "arc: primary program 'arc' not found"
+        echo "Consider visiting documentation page at 'https://docs.yandex-team.ru/devtools/intro/quick-start-guide' for more details"
+        exit 1
+    fi
+
+    local suggested_path=$(echo "$paths" | head -1)
+    if [[ -z "$ARC_PRIMARY_PATH" ]]; then
+        echo 'arc: path to primary program `ARC_PRIMARY_PATH` is not set'
+        echo "Consider adding \`export ARC_PRIMARY_PATH=$suggested_path\` to your shell configuration file"
+        exit 1
     fi
 }
 
